gramo-org/echo_common

lib/echo_common/configuration.rb
lib/echo_common/middleware/request_id.rb
lib/echo_common/rspec/helpers/jwt_auth_helper.rb
spec/lib/lotus/controllers/authentication_spec.rb

connected to gramo-org/echo#11

added RequestId middleware and added request_id tag to logger

---

lib/echo_common/paginatable_array.rb
spec/lib/paginatable_array_spec.rb

Vi trenger et objekt som kan holde en liste og samtidig noe metadata om begrensning lagt på listen, offset og totalt antall man kan forvente.

Added EchoCommon::PaginatableArray.

---

lib/echo_common/time_zone.rb
spec/lib/time_zone_spec.rb

Støtte å opprette tidsobjekter med en spesifikk tidssone.

TimeZone.in_time_zone { ...exec code... }

---

echo_common.gemspec
lib/echo_common/services/elasticsearch.rb
lib/echo_common/services/elasticsearch/client.rb
lib/echo_common/services/elasticsearch/operations/crud.rb
lib/echo_common/services/elasticsearch/operations/index.rb
lib/echo_common/services/elasticsearch/operations/query.rb
spec/lib/services/elasticsearch/client_spec.rb

connected to https://github.com/gramo-org/echo/issues/268

moved elasticsearch service base from echo to echo_common

---

lib/echo_common/rspec/helpers/elasticsearch_helper.rb
lib/echo_common/services/elasticsearch.rb

connected to https://github.com/gramo-org/echo/issues/268

Reuse elasticsearch spec helper

---

lib/echo_common/services/elasticsearch.rb
lib/echo_common/services/elasticsearch/client.rb
lib/echo_common/services/elasticsearch/operations/query.rb

connected to https://github.com/gramo-org/echo/issues/268

Add query index option to elastic service

---

lib/echo_common/entity.rb
lib/echo_common/recording_draft.rb
lib/echo_common/recording_draft_repository.rb

Add RecordingDraft and RecordingDraftRepository

---

lib/echo_common/entity.rb

The code did not work together with the "hanami-model inherit attributes bug" fix

Fix issue with Entity::read_only_attributes

---

lib/echo_common/recording_draft.rb

Connected to gramo-org/echo#313

Add composers to recording draft

---

lib/echo_common/services/elasticsearch/operations/crud.rb
spec/lib/services/elasticsearch_spec.rb

connected to https://github.com/gramo-org/echo/issues/463

raise eror with payload if bulk response has errors

---

lib/echo_common/recording_draft.rb

Connected to https://github.com/gramo-org/echo/issues/464

Hovedartist som én tekststreng

---

config/elasticsearch_indices/recording_drafts.json
lib/echo_common/services/elasticsearch/client.rb
spec/lib/services/elasticsearch/client_spec.rb

Array to be more flexible, as some applications has it's own globing pattern too.
Connected to https://github.com/gramo-org/tube_tube/issues/141

Added common recording_drafts index config + Indices mapping glob can be array

---

echo_common.gemspec
lib/echo_common/configuration.rb
lib/echo_common/hanami/controllers/jwt.rb
lib/echo_common/logger/formatter.rb
spec/lib/configuration_spec.rb
spec/lib/hanami/controllers/jwt_spec.rb

For applications not yet upgraded they can track branch `hanami-pre-0.8`.

Use Hanami 0.8

---

.rubocop_todo.yml
lib/echo_common/hanami/controllers/authentication.rb
lib/echo_common/hanami/controllers/jwt.rb
spec/lib/hanami/controllers/authentication_spec.rb
spec/lib/hanami/controllers/jwt_spec.rb

Asking if an invalid token is authenticated returns simply false.

JWT hanami controller integration don't raise error on invalid token.

---

echo_common.gemspec
lib/echo_common/services/elasticsearch/client.rb

ssia
connected to https://github.com/gramo-org/echo/issues/1104

add typhoeus for persistent http keep-alive

---

lib/echo_common/rspec/helpers/elasticsearch_helper.rb

This is now unused as we have moved away from SnapCI.

Remove all traces of TestCluster

---

lib/echo_common/rspec/helpers/db_clean_helper.rb

I recommend reading the commit messages. :)

Transaction around blocks

---

lib/echo_common/recording_draft.rb

Lägger till ett "contributors"-fält i echo_common, vilket påverkar både tube_tube och echo.

Add contributors to recording_draft

---

lib/echo_common/rspec/helpers/elasticsearch_helper.rb

should fix issue with leaking state when using guard

ensure clear state and use class variable for indices_setup state

---

config/elasticsearch_indices/recording_drafts.json
lib/echo_common/recording_draft.rb

connected to https://github.com/gramo-org/echo/issues/1580

add recorded_in to draft

---

lib/echo_common/configuration.rb

Trenger dette konkret nå for å teste at brudd på tilgangskontroll blir logget.

Make logg write to a StringIO object if environment is test

---

config/elasticsearch_indices/release_drafts.json
lib/echo_common/elasticsearch_base_repository.rb
lib/echo_common/recording_draft_repository.rb
lib/echo_common/release_draft.rb
lib/echo_common/release_draft_repository.rb

https://github.com/gramo-org/echo/issues/2794
This follows the pattern of what we did with recording draft.

Release draft

---

lib/echo_common/services/elasticsearch/client.rb
spec/lib/services/elasticsearch/client_spec.rb

Required for searching over release and drafts.

Support list of indexes for elasticsearch to search across

---

lib/echo_common/services/elasticsearch/operations/crud.rb

Will hopefully make it possible to debug gramo-org/echo#3060

Add response errors to BulkError message

---

lib/echo_common/duration.rb
spec/lib/duration_spec.rb

https://github.com/gramo-org/echo/issues/3126

Addeds support for generate a ISO 8601 string from duration.

---

lib/echo_common/services/elasticsearch/client.rb
spec/lib/services/elasticsearch/client_spec.rb

Add `put_mapping` and `update_by_query` actions to elasticsearch client
Check: https://github.com/gramo-org/echo/issues/3371

Add new actions to elasticsearch client

---

lib/echo_common/services/elasticsearch/client.rb
spec/lib/services/elasticsearch/client_spec.rb

Add a method for listing tasks

---

lib/echo_common/services/elasticsearch/client.rb

Same as last time (ref. https://github.com/gramo-org/echo_common/pull/64).
I really think that this tedious and that this could be done easier using submodules, which would allow a developer to make local changes without having to push to a test branch upstream.

Passthrough all unknown Elastic options

---

lib/echo_common/services/elasticsearch/operations/crud.rb

Required by https://github.com/gramo-org/echo/pull/3843

Allow elasticsearch bulk requests to receive more options (e.g refresh)

---

lib/echo_common/uri_helpers.rb
spec/lib/uri_helpers_spec.rb

For now the only method is #add_query_variables

Add a UriHelpers module

---

lib/echo_common/services/elasticsearch/client.rb
spec/lib/services/elasticsearch/client_spec.rb

- Add raising error when index errors are found
More context can be found here: https://github.com/gramo-org/echo/issues/4810#issuecomment-547422838
Connected to https://github.com/gramo-org/echo/issues/4810

Feat: Add raising error when index errors are found

---

lib/echo_common/services/elasticsearch/operations/crud.rb
spec/lib/services/elasticsearch_spec.rb

Connected to https://github.com/gramo-org/echo/issues/4933

fix: don't index id itself in doc. Only use _id metafield

---

lib/echo_common/services/elasticsearch/operations/crud.rb
lib/echo_common/services/elasticsearch/operations/merge_in_id.rb
lib/echo_common/services/elasticsearch/operations/query.rb
spec/lib/services/elasticsearch_spec.rb

https://github.com/gramo-org/echo/issues/4933

refactor: lets leverage some ruby in es crud module

---

lib/echo_common/services/elasticsearch/client.rb

this change appears to work fine in 5.6 and 6.8. In theory we can merge this before everything else so it is ready for 6.8.

fix: update suggest to use the search api

---

config/elasticsearch_indices/recording_drafts.json.erb
lib/echo_common/recording_draft.rb

Connected to gramo-org/echo#5338

Add P line to recording drafts

---

spec/lib/entity/relation/many_spec.rb

This error does not seem to be raised in a test in Echo, so I
wanted to make sure the behaviour is working. May as well add
the test now it written.

Added a spec for duplicate Entity objects of different instances

---

.github/workflows/test.yml
codeship-services.yml
codeship-steps.yml

Connected to gramo-org/echo#7501

Migrate tests to run on github actions
