gramo-org/echo_common

- lib/echo_common/configuration.rb
- lib/echo_common/logger/formatter.rb
- spec/lib/configuration_spec.rb
- spec/spec_helper.rb
Since some loggers are created before requests, and lives during the
time span of the server, it didn't work to evaluate the thread
echo_request_id during initialization.
The evaluation has to be deferred to the write time.
> Fixed request_id on progname for logger.

- lib/echo_common/time_of_day.rb
- spec/lib/time_of_day_spec.rb
Introduserer en klasse for å representere på tid på døgnet, uten dato eller tidssone. Til bruk for for eksempel programmer som gjentas, med fast start- og slutt tidspunkt.
Klassen har `load` og `dump`, så vi kan benytte den sammen med Lotus for innlesing og dumping av verdi fra databasen.
Den støtter enkel `+/-` operasjon, er sammenlignbar og kan benyttes i range ala `(t1..t2).include? t3`
> Time of day

- lib/echo_common/hanami/models/coercer/pg_array.rb
- spec/lib/hanami/models/coercer/pg_array_spec.rb
Hanami mapping var ikke så glad i instanser, da den forventer en klasse.
Endret slik at factory returnerer en dynamisk klasse i samme namespace som arver fra PGArray.
Eksempel på bruk i mapping:
```
attribute :main_artists, ::EchoCommon::Hanami::Models::Coercer::PGArray.for(:varchar)
```
connected to https://github.com/gramo-org/echo/issues/188
> create dynamic class for type

- lib/echo_common/services/elasticsearch/client.rb
- spec/lib/services/elasticsearch/client_spec.rb
This way it is easier to pass in other options than only configuration
for the host. We can also fill in request timeouts etc as if it is the
"native" elastic search gem's client.
We also delete arguments our client cares about so they don't get in to
the elastic's client new argument list.
> EchoCommon elastic client#new has equal arguments as elastic gem.

- lib/echo_common/entity/relation/many.rb
- spec/lib/entity/relation/many_spec.rb
Klasse for representasjon av en-til-mange relasjoner.
Trukket ut kode vi brukte i [program relasjon fra echo](https://github.com/gramo-org/echo/blob/add-group/lib/echo/playtime_registry/entities/channel/program_relation.rb) da vi og trenger liknende konstruksjon for å representere [groppe medlemsskap relasjon](https://github.com/gramo-org/echo/blob/add-group/lib/echo/discography/entities/group/membership_relation.rb).
> En-til-mange relasjon

- lib/echo_common/hanami/controllers/authentication.rb
- lib/echo_common/rspec/helpers/jwt_auth_helper.rb
Exposes the current user locale from the jwt token through the authentication controller.
related to https://github.com/gramo-org/echo/pull/977
> add current user locale to authentication controller

- lib/echo_common/hanami/models/coercer/pg_array.rb
- spec/lib/hanami/models/coercer/pg_array_spec.rb
While adding support for types with space in name, like [timestamp with time zone](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/extensions/pg_array.rb#L531) i noticed the implementation was fundamentally broken. When I wrote this I was pretty fresh to ruby, and I though class variables were unique for a class, but Ruby class variables are in fact class hierarchy variables, meaning they are shared between all descendants of a class. So what was happening here was that all descendant classes where referencing the same variable, and the last call to PGArray.for was changing the value for all descendants. 
I added some tests proving the behaviour and fixed the implementation.
The diff has some whitespace changes, so can be better viewed with this: …
> Fix pg array.for

- lib/echo_common/state_machine/machine.rb
- spec/lib/state_machine/machine_spec.rb
This worked if the initial state was possible to transition to, but when
init state only was an initial state no predicate method was created.
> Fixed bug with state machine predicate for initial state.

- lib/echo_common/entity.rb
- spec/lib/entity_spec.rb
This allows for the entity to be used as a key in a hash.
https://github.com/rails/rails/blob/c83f28fffe8b18ee75822394a11f446c05f692fd/activerecord/lib/active_record/core.rb#L432
was used as an inspiration.
Also fixed `#==` and `#eql?`
> Entity#hash is same for all objects of same class and with same id + equality fixes

- lib/echo_common/hanami/controllers/authentication.rb
- lib/echo_common/hanami/controllers/jwt.rb
- lib/echo_common/rspec/helpers/jwt_auth_helper.rb
- spec/lib/hanami/controllers/authentication_spec.rb
To make https://github.com/gramo-org/echo/pull/2530 work.
- Rescue `JWT::DecodeError`, not only `ExpiredSignature`. For the onboard controller the `token` param includes a non-JWT token, which makes the code trip when we try to extract locale attribute from that token. I think if we fail decode for some reason we consider user not to be authenticated is ok(?).
- Default locale in test helper is `en`.
> En as default locale for test user

- lib/echo_common/time_of_day.rb
- spec/lib/time_of_day_spec.rb
I'm not sure if this has ever worked as expected. Seems to me that we store XML formatted strings in our database, like:
```sql
select created_at, data from events where name = 'playtime_report_airing_gap_detected_ignored' and aggregate_type = 'Echo::Model::PlaytimeRegistry::Entities::PlaytimeReport' order by id asc limit 1;
created_at         |                                        data
----------------------------+------------------------------------------------------------------------------------
2017-08-30 09:54:29.865746 | {"ends_at": "2016-01-06T18:00:00+01:00", "starts_at": "2016-01-06T17:57:00+01:00"}
```
The string `2016-01-06T17:57:00+01:00` is passed in to the `TimeOfDay::load` during some part of the deviation detection. It occurred when we re-read a playtime report already …
> TimeOfDay::load supports xmlschema formatted timestamps.

- config/elasticsearch_indices/recording_drafts.json
Add `raw` keyword fields to recording_drafts ES index. Needed for exact search implemented here: https://github.com/gramo-org/echo/pull/3359
> Add raw fields to recording_drafts ES index

- lib/echo_common/services/elasticsearch/client.rb
This method will return the ID of the created task, which we sometimes want.
> Symbolize the return value of #update_by_query

- lib/echo_common/services/elasticsearch/client.rb
- spec/lib/services/elasticsearch/client_spec.rb
Allow update action to take option regarding updating partially via script.
In case of conflict - version mismatches, this option can be used to retry the update.
Especially useful when updating same documents by multiple clients.
See: https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-updates.html#_updates_and_conflicts
> Add retry on conflict option to elasticsearch update method

- lib/echo_common/services/elasticsearch/client.rb
The Elastic library will decide what options are good and not. We only care about the ones we specifically do something out of the ordinary with, such as prefixing.
I need this for invoking `update_by_query` with a body.
> Passthrough all unknown Elastic options

- lib/echo_common/elasticsearch/restore_wait_on_completion.rb
- spec/lib/elasticsearch/restore_wait_on_completion_spec.rb
We need to query the recovery api for the cluster in order to figure out
if we have completed and restored every index.
We found no way to figure this out via elasticsearch's task api, as it
only seems to be listed there if the restore request itself has
wait_for_completion=true. We need to wait longer than the gateway of
cloud.elastic.co allows in order to restore production indices, so this
code allows us to wait by polling.
Connected to https://github.com/gramo-org/echo/issues/4066
> feat: added an elasticsearch restore wait-on-completion helper.

- echo_common.gemspec
Related to this PR: https://github.com/gramo-org/echo/pull/4270
New version of `nexmo` gem that we're using depends on `~> 2` version for `jwt`, which results into conflict in `echo_common` during `bundle install`.
> update jwt gem to 2.x version

- config/elasticsearch_indices/recording_drafts.json.erb
- config/elasticsearch_indices/release_drafts.json.erb
Reverts gramo-org/echo_common#71
We decided not to do anything with release year for drafts for now ([more info in comment and below here](https://github.com/gramo-org/min-side/issues/782#issuecomment-493038559)).
> Revert "Add release_year to release_drafts and recording_drafts"

- config/elasticsearch_indices/recording_drafts.json.erb
- config/elasticsearch_indices/release_drafts.json.erb
- Add new raw fields to label_name and catalog_number in release_drafts mapping to allow sorting by them in min-side global search
Connected to https://github.com/gramo-org/min-side/issues/783
Echo PR: https://github.com/gramo-org/echo/pull/4336
> Add new raw fields to release_drafts mapping

- lib/echo_common/hanami/models/coercer/ip_addr.rb
- spec/lib/hanami/models/coercer/ip_addr_spec.rb
Previously it had to be a string or nil, but as sequel_pg now returns
IPAddr objects when a row is read from the DB we must support this too.
Relates to https://github.com/gramo-org/echo/issues/4442
> fix: IPAddr::load works given an IPAddr object

- config/elasticsearch_indices/recording_drafts.json.erb
- config/elasticsearch_indices/release_drafts.json.erb
Add case_insensitive normalizer to recording/release drafts elasticsearch mapping for sorting
Connected to https://github.com/gramo-org/min-side/issues/783#issuecomment-498616893
Echo: https://github.com/gramo-org/echo/pull/4452
> Add case_insensitive normalizer to recording/release drafts to sort on

- config/elasticsearch_indices/recording_drafts.json.erb
- config/elasticsearch_indices/release_drafts.json.erb
Add unify_apostrophes_analyzer to recording/release drafts indices
Echo: https://github.com/gramo-org/echo/pull/4676
Related issue: gramo-org/min-side#222
> Feat: Add unify_apostrophes_analyzer to recording/release drafts indices

- lib/echo_common/services/elasticsearch/client.rb
- spec/lib/services/elasticsearch/client_spec.rb
Our reason for requiring this is that we have repositories in Echo,
which works towards recordings index to find recordings with given
producer owner ids.
The thing which complicates it is that this recording repository
actually works towards a @discography alias which spans over recordings
and discography_drafts index.
The draft index does not have the same fields as the recording in
regards to for instance ownerships.
So when we introduced the IndexShardsError error it made this code in
Echo fail.
The IndexShardsError was introduced back in October 2019, but didn't
make its way in to Echo before now :-(
Connected to https://github.com/gramo-org/echo/pull/4936#issuecomment-572459485
Connected to https://github.com/gramo-org/echo/issues/4933
Related to …
> feat(elastic): suppress shards failures when searching

- lib/echo_common/services/elasticsearch/operations/crud.rb
- spec/lib/services/elasticsearch_spec.rb
This reverts the change that got introduced to fix https://github.com/gramo-org/echo/issues/4933. Gramo needs to be able to search for IDs, so we will instead update the mapping of the index (by reindexing) to solve this problem.
> Elasticsearch: Don't delete IDs from documents when indexing

- lib/echo_common/rspec/helpers/db_clean_helper.rb
In some tests, we might ensure that a transaction has been rolled back (e.g. if
an error occurred). Since currently we do not support transactions within other
transactions, those tests use the `omit_database_transaction` flag which means
the test does not get wrapped in a transaction. The problem is that these tests
now leave data lying around after running.
Our original plan to solve this was to find a way to still rollback in the app
despite already running in a transaction. However Sequel does not support naming
a transaction from what I can tell, and anyway there is no way to pass args to
the transaction via the `DatabaseCleaner` gem. Going through some issues I found
this issue:
https://github.com/DatabaseCleaner/database_cleaner/issues/652
Basically this person wants to read data …
> fix: Ensure the DB is still "cleaned" even when transactions are not used

- config/elasticsearch_indices/recording_drafts.json.erb
- config/elasticsearch_indices/release_drafts.json.erb
- lib/echo_common/recording_draft.rb
Currently we rely on local ids in echo to store the connection between an echo
recording and the draft it is based on. The problem is that we "retire" entries
when new data about a release/recording comes in, and we would like to "clean"
that old data without breaking the connection to echo.
The plan is to actually replace the ID in ES with the external foreign key, but
since release already had this field I figured I may as well add it anyway, we
can always remove it later. I also "fixed" the types we use to be `keyword`.
Connected to https://github.com/gramo-org/echo/issues/5434
> Add "external_foreign_key" to recordings

- lib/echo_common/rspec/helpers/elasticsearch_helper.rb
- lib/echo_common/services/elasticsearch.rb
It was pretty broken, and we don't use it anymore.
> Remove the query alias functionality

- lib/echo_common/rspec/helpers/elasticsearch_helper.rb
When using the ES client directly, we get the index names which includes the prefix. We thus need to remove the prefix if it exists when keeping track of dirty indices.
> Make the ES rspec helper aware of index prefixes

- lib/echo_common/services/elasticsearch/client.rb
I am adding a new elasticsearch projection for foreign remuneration snapshot
groups in echo. One requirement is to delete all groups belonging to a specific
snapshot when that snapshot is deleted, or fails to build.
Rather than loading all the groups and looping each one to delete them, it is
more efficient to have the deletion done on the elasticsearch side, since this
will reduce the chance of race conditions and require less network overhead.
Connected to https://github.com/gramo-org/echo/issues/5740
> Add `delete_by_query` elasticsearch method

- lib/echo_common/services/elasticsearch/client.rb
I created a new mapping file: foreign_remuneration_snapshot_groups.json.erb
Unfortunately, if the the `groups` index needed to be created, it would find my
mapping file too since it also ends in `groups.json.erb`. Lets just say this was
not fun to debug.
Connected to https://github.com/gramo-org/echo/issues/5740
> fix: Allow mapping files to share the same ending

- lib/echo_common/entity/relation/many.rb
- spec/lib/entity/relation/many_spec.rb
When we have large collections, using `include?` requires checking the whole
array every time a new item is added, which kill performance. Using a `Set`
means it takes a fraction of the time.
Also, `eq?` is not a method on arrays, so I have removed it.
Connected to https://github.com/gramo-org/echo/issues/6287
> Use a set in the `Entity::Relation::Many` class for much better performance

- lib/echo_common/entity/relation/many.rb
- spec/lib/entity/relation/many_spec.rb
In echo, one unit test failed, because two Programs shared the same ID. Turns
out that the `AlreadyAddedError` error was not raised in the `before` block,
because it was doing the following:
```ruby
subject << program_music << program_news << program_unicode
```
Since `<<` was returning `@collection`, the second `<<` was using the `push`
method on the `Set` directly.
For some reason, the following does not work:
```ruby
expect(subject).to equal subject
```
Which is why I am checking `object_id` and `class` directly
> Ensure we return `self` from `push` method

- lib/echo_common/rspec/helpers/db_clean_helper.rb
Sometimes people use staging database URL as their local DB to test some performance issues, etc. In this case we don't want tests to do anything with DB data.
Connected to https://github.com/gramo-org/echo/issues/6650
> Make sure we only truncate database with "_test" in the name.
